# Generated by Django 3.2.4 on 2021-06-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('urbana', 'Parroquia Urbana'), ('rural', 'Parroquia Rural')], max_length=30)),
            ],
            options={
                'verbose_name_plural': 'La Parroquias',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('número_viviendas', models.IntegerField()),
                ('número_parques', models.CharField(max_length=50)),
                ('número_edificios', models.IntegerField()),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='ordenamiento.parroquia')),
            ],
        ),
    ]
