# Generated by Django 3.2.4 on 2021-06-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrio',
            name='número_parques',
            field=models.IntegerField(choices=[(0, 'Ninguno'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')]),
        ),
        migrations.AlterField(
            model_name='parroquia',
            name='tipo',
            field=models.CharField(choices=[('urbano', 'Parroquia Urbana'), ('rural', 'Parroquia Rural')], max_length=30),
        ),
    ]
